version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: my_medusa_db
      POSTGRES_USER: piwu
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
