version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: medusa123
      POSTGRES_DB: medusa_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  medusa:
    build:
      context: backend
    container_name: medusa_backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://backend:medusa123@postgres:5432/medusa_db
      REDIS_URL: redis://redis:6379
      NODE_ENV: development
      JWT_SECRET: your_jwt_secret
      COOKIE_SECRET: your_cookie_secret
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    working_dir: /app
    command: yarn dev

volumes:
  pg-data:
