version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: medusa_postgres
    environment:
      POSTGRES_DB: my_medusa_db
      POSTGRES_USER: piwu
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  init-db:
    image: alpine
    volumes:
      - ./db-data.tar.gz:/backup/db-data.tar.gz
      - ./pgdata:/restore-target
    entrypoint: >
      sh -c "
        apk add --no-cache tar &&
        if [ ! -f /restore-target/PG_VERSION ]; then
          echo '[init-db] Restoring database from archive...' &&
          mkdir -p /restore-target &&
          tar -xzf /backup/db-data.tar.gz -C /restore-target &&
          echo '[init-db] Done.'
        else
          echo '[init-db] pgdata already initialized, skipping restore.'
        fi
      "
    restart: "no"

  backend:
    build:
      context: ./backend
    container_name: medusa_backend
    working_dir: /app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://piwu:password@postgres:5432/my_medusa_db
      JWT_SECRET: supersecret
      COOKIE_SECRET: cookiesecret
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - init-db
    ports:
      - "9000:9000"
    command: yarn dev

  storefront:
    build:
      context: ./storefront
    container_name: medusa_storefront
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: node .output/server/index.mjs
